config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :pay_periods

  resources :work_days
  root 'access#login'
  get 'access/attempt_login' => 'access#attempt_login'
  post 'access/attempt_login' => 'access#attempt_login'
  get 'punches/index' => 'punches#index'
  get 'punches/clock_in' => 'punches#clock_in'
  post 'punches/clock_in' => 'punches#clock_in'
  get 'punches/clock_out' => 'punches#clock_out'
  post 'punches/clock_out' => 'punches#clock_out'
end

app/models/pay_period.rb
class PayPeriod < ActiveRecord::Base
  has_many :work_days
end

app/models/punch.rb
class Punch < ActiveRecord::Base

  belongs_to :user
  belongs_to :work_day

  def clock_in
    # self.update_attributes(in: DateTime.now)
    Punch.last.update_attributes(in: DateTime.now)
  end

  def clock_out
    Punch.last.update_attributes(out: DateTime.now)
    # self.update_attributes(out: DateTime.now)
  end

  def time_worked
    ((self.out - self.in) / 3600).round(2)
  end

  # def in_format
  #   self.in.strftime('%I:%M:%S %p on %a %b %d %Y')
  # end
  #
  # def out_format
  #   self.out.strftime('%I:%M:%S %p on %a %b %d %Y')
  # end


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :punches
  has_many :work_days

  has_secure_password validations: false

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/work_day.rb
class WorkDay < ActiveRecord::Base
  belongs_to :user
  belongs_to :pay_period
  has_one :punch
  def time_worked
    ((self.out - self.in) / 3600).round(2)
  end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  before_action :confirm_logged_in, except: [:login, :attempt_login, :logout]

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    if authorized_user
      session[:user_id] = authorized_user.id
      redirect_to user_path(session[:user_id])
    else
      redirect_to(controller: 'access', action: 'login')
    end
  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = "Logged out"
    redirect_to(action: "login")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index

  end

  def confirm_logged_in
    unless session[:user_id]
      redirect_to(controller: 'access', action: 'login')
      return false
    else
      return true
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pay_periods_controller.rb
class PayPeriodsController < ApplicationController
  def index
    @pay_periods = PayPeriod.all
  end

  def show
    @pay_period = PayPeriod.find(params[:id])
    @work_days = @pay_period.work_days.where(user_id: current_user.id)
  end

  def new
    @pay_period = PayPeriod.new
  end

  def create
    @pay_period = PayPeriod.create(pay_period_params)
  end

  def edit
    @pay_period = PayPeriod.find(params[:id])
  end

  def update
    @pay_period = PayPeriod.find[params[:id]]
    @pay_period.update_attributes(pay_period_params)
  end

end

app/controllers/punches_controller.rb
class PunchesController < ApplicationController
  def index
    @punches = Punch.all
  end

  def clock_in
    @work_day = WorkDay.create(user_id: current_user.id, pay_period_id: PayPeriod.first.id)
    @punch = Punch.create(in: DateTime.now, user_id: current_user.id, work_day_id: @work_day.id)
    @punch.user.update_attributes(clocked_in: true)
    flash[:notice] = "Successfully clocked in at " + "#{@punch.in.strftime('%I:%M %p')}"
    redirect_to :back
  end

  def clock_out
    @punch = Punch.last
    @punch.update_attributes(out: DateTime.now)
    @punch.user.update_attributes(clocked_in: false)
    flash[:notice] = "Successfully clocked out at " + "#{@punch.out.strftime('%I:%M %p')}"
    redirect_to :back
  end

  def create
    punch.create(punch_params)
  end

  private

  def punch_params
    params.require(:punch).permit(:in, :out).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @pay_periods = PayPeriod.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user.update_attributes(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :clocked_in)
  end

end

app/controllers/work_days_controller.rb
class WorkDaysController < ApplicationController
  def index
    @work_days = WorkDay.where(user_id: current_user.id)
  end

  def show
    @work_day = WorkDay.where(id: params[:id], user_id: current_user.id).first
  end

  def new
    @work_day = WorkDay.new
  end

  def create
    @work_day = WorkDay.new

    if @work_day.save
      redirect_to 'index'
    else
      render 'new'
    end
  end

  def edit
    @work_day = WorkDay.find(params[:id])
  end

  def update
    @work_day = WorkDay.find(params[:id])

    if @work_day.update_attributes
      redirect_to 'index'
    else
      render 'edit'
    end
  end

  private

  def work_day_params
    params.require(:work_day).permit(:work_date).merge(:user_id)
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pay_periods_helper.rb
module PayPeriodsHelper
end

app/helpers/punches_helper.rb
module PunchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_days_helper.rb
module WorkDaysHelper
end

app/views/access/login.html.erb
<div class="login">
  <%= form_tag(action: 'attempt_login') do %>
    <table>
      <tr>
        <td><%= label_tag(:username) %></td>
        <td><%= text_field_tag(:username) %></td>
      </tr>
      <tr>
        <td><%= label_tag(:password) %></td>
        <td><%= password_field_tag(:password) %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><%= submit_tag("Log In") %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/application/index.html.erb
<%= link_to "Log in", '#' %>
<%= button_to "clock_in", controller: 'punches', action: "clock_in" %>
<%= button_to "clock_out", controller: 'punches', action: "clock_out" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schedule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if !flash[:notice].blank? %>
    <%= flash[:notice] %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/pay_periods/edit.html.erb
<h1>PayPeriods#edit</h1>
<p>Find me in app/views/pay_periods/edit.html.erb</p>

app/views/pay_periods/index.html.erb
<% @pay_periods.each do |f| %>
 <%= link_to "#{f.work_days.first.work_date.strftime('%a %b %d %Y')} - #{f.work_days.last.work_date.strftime('%a %b %d %Y')}", pay_period_path(f) %>
<% end %>

app/views/pay_periods/new.html.erb
<h1>PayPeriods#new</h1>
<p>Find me in app/views/pay_periods/new.html.erb</p>

app/views/pay_periods/show.html.erb
<h1><%= "#{@pay_period.work_days.first.work_date.strftime('%a %b %d %Y')} - #{@pay_period.work_days.last.work_date.strftime('%a %b %d %Y')}" %></h1>

<% @work_days.each do |f| %>
<% if f %>
  <%= link_to f.work_date.strftime('%a %b %d %Y'), work_day_path(f) %> Hours Worked: <%= f.punch.time_worked %><br>
  <% end %>
<% end %>

app/views/punches/index.html.erb
<%= button_to "clock_in", action: "clock_in" %>
<%= button_to "clock_out", action: "clock_out" %>
<h1><%= @punches.last.in.strftime('%a %b %d %Y') %></h1>
<div class="in">
  <h1>In</h1>

  <%= @punches.last.in.strftime('%I:%M:%S %p on %a %b %d %Y') %>
</div>

<div class="out">
  <h1>Out</h1>
  <% if @punches.last.out? %>
  <%= @punches.last.out.strftime('%I:%M:%S %p on %a %b %d %Y') %>
  <% end %>
</div>

<div class="time_worked">
  <h1>Time</h1>
  <% if @punches.last.out? %>

  You have worked: <%= @punches.last.time_worked %> hours today.
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if @user.clocked_in %>
  <%= button_to "clock_out", controller: 'punches', action: "clock_out" %>
<% else %>
  <%= button_to "clock_in", controller: 'punches', action: "clock_in" %>
<% end %>
<h1>Pay Periods</h1>
<% @pay_periods.each do |f| %>
  <% if f.work_days.first %>
   <%= link_to "#{f.work_days.first.work_date.strftime('%a %b %d %Y')} - #{f.work_days.last.work_date.strftime('%a %b %d %Y')}", pay_period_path(f) %>
   <br>
  <% else %>
    No recorded time...
  <% end %>
<% end %>

app/views/work_days/edit.html.erb
<h1>WorkDays#edit</h1>
<p>Find me in app/views/work_days/edit.html.erb</p>

app/views/work_days/index.html.erb
<h1>Days in this pay period..</h1>
<% @work_days.each do |day| %>
  <%= link_to day.work_date.strftime('%a %b %d %Y'), work_day_path(day) %>
  <br>
<% end %>

app/views/work_days/new.html.erb
<h1>WorkDays#new</h1>
<p>Find me in app/views/work_days/new.html.erb</p>

app/views/work_days/show.html.erb
<% if @work_day %>
  <h1><%= @work_day.work_date.strftime('%a %b %d %Y') %></h1>

    <h2>In</h2>
    <%= @work_day.punch.in.strftime('%I:%M:%S %p') %>
    <h2>out</h2>
    <% if @work_day.punch.out %>
      <%= @work_day.punch.out.strftime('%I:%M:%S %p') %>
      <div class="time_worked">
        <h1>Time</h1>
        <%=@work_day.punch.time_worked %> hours.
      </div>
    <% else %>
      pending...
    <% end %>


<% else %>
  No time logged yet.
<% end %>